root: true
parser: "@babel/eslint-parser"
extends:
  - standard
  - standard-jsx
  - standard-react
plugins:
  - import
  - simple-import-sort
rules:
  react/prop-types: "off"
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  import/extensions: [error, always, { ignorePackages: true }]
env:
  node: true
